# Generated by Django 2.1.3 on 2018-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20181111_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
