# Generated by Django 2.1.3 on 2018-11-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_ticket_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='confirmed_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
